### ISSUE TITLE
Context menu of featured items in the Featured page always shows 'feature'

### ISSUE THREAD

**Issue by mcbloch** [ZeusWPI/g2-frontend#56] opened 2020-07-31 17:38 UTC
The context menu behaves correctly in the issues tab. It says feature for unfeatured items unfeature for featured items.
In the featured tab it should always say 'unfeature' but it says 'feature'.

**Comment by maartenvn** [comment] 2020-08-05 06:28
@mcbloch This is an issue caused by the backend. No `featured` property is passed on the `data` property of the `/features` endpoint.

**Comment by maartenvn** [comment] 2020-08-05 06:32
Some other properties are not passed as well.

**Comment by maartenvn** [comment] 2020-08-05 16:15
Closing this since it is a backend issue

**Closed as completed by maartenvn** 2020-08-05 16:15 UTC
Labels: bug
